var searchData=
[
  ['g_0',['g',['../namespaceposteriors.html#a0b62d5333063944bd4a307c2d2dd76c4',1,'posteriors']]],
  ['getempiricaldistributions_1',['getEmpiricalDistributions',['../util_8h.html#ab492700b8d4d51252d43590949ba1b6f',1,'getEmpiricalDistributions(std::map&lt; int, std::vector&lt; aDDMTrial &gt; &gt; data, int timeStep=10, int MaxFixTime=3000, int numFixDists=3, std::vector&lt; int &gt; valueDiffs={-3,-2,-1, 0, 1, 2, 3}, std::vector&lt; int &gt; subjectIDs={}, bool useOddTrials=true, bool useEvenTrials=true, bool useCisTrials=true, bool useTransTrials=true):&#160;util.cpp'],['../util_8cpp.html#a1a09b053b0688ac92f3f6b9d5af66a2a',1,'getEmpiricalDistributions(std::map&lt; int, std::vector&lt; aDDMTrial &gt; &gt; data, int timeStep, int MaxFixTime, int numFixDists, std::vector&lt; int &gt; valueDiffs, std::vector&lt; int &gt; subjectIDs, bool useOddTrials, bool useEvenTrials, bool useCisTrials, bool useTransTrials):&#160;util.cpp']]],
  ['gettriallikelihood_2',['getTrialLikelihood',['../classa_d_d_m.html#a9ccee0abe15711f09f8eee0a782f3e06',1,'aDDM::getTrialLikelihood()'],['../class_d_d_m.html#a025072ab3fd16dee3a0b0f57c7585a06',1,'DDM::getTrialLikelihood()']]],
  ['gettriallikelihoodkernel_3',['getTrialLikelihoodKernel',['../cuaddm_8cu.html#acca1227e05acdd3fca7f8a776d1767ae',1,'getTrialLikelihoodKernel(bool debug, int trialsPerThread, int *RTs, int *choices, int *valLs, int *valRs, int *FixItemsMatrix, int *FixTimeMatrix, int *FixLens, double *likelihoods, int numTrials, float *states, int maxFixLen, int biasState, int numStates, float stateStep, float d, float sigma, float theta, int barrier, int nonDecisionTime, int timeStep, float approxStateStep, float dec):&#160;cuaddm.cu'],['../cuddm_8cu.html#a59cb523fef27295f28a7ffaf09279014',1,'getTrialLikelihoodKernel(bool debug, int trialsPerThread, int *RTs, int *choices, int *valDiffs, double *likelihoods, int numTrials, float *states, int biasState, int numStates, float stateStep, float d, float sigma, int barrier, int nonDecisionTime, int timeStep, float approxStateStep, float dec):&#160;cuddm.cu']]],
  ['gpu_5ftoolbox_2eh_4',['gpu_toolbox.h',['../gpu__toolbox_8h.html',1,'']]],
  ['gpuinvalid_5',['gpuInvalid',['../util_8h.html#a14a86a1ac143b9422bb8732c68acb5ab',1,'gpuInvalid:&#160;util.cpp'],['../util_8cpp.html#a14a86a1ac143b9422bb8732c68acb5ab',1,'gpuInvalid:&#160;util.cpp']]]
];
